on:
  push:
    branches:
    - master

jobs:
  test:
    name: run unit test
    runs-on: ubuntu-22.04
    steps:
      - name: run unit test
        run: |
          echo "misalnya ini akan running unit test"
      - name: list file
        run: |
          ls -la
      - name: clone repository
        uses: actions/checkout@v4
      - name: list file lagi
        run: |
          ls -la

  build:
    name: build app
    needs:
    - test
    runs-on: ubuntu-22.04
    steps:
      - name: run build app
        run: |
          echo "misalnya ini akan build aplikasi"

  deploy:
    name: deploy app to server
    runs-on: ubuntu-22.04
    needs:
    - test
    - build
    steps:
      - name: run deploy
        run: |
          echo "misalnya ini akan deploy aplikasi ke server"